name: Build AutoGPTQ Wheels

on: workflow_dispatch

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade build setuptools wheel

      - name: Build Wheel
        run: |
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: 'sdist'
          path: ./dist/*.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: 'no-cuda-wheel'
          path: ./dist/*.whl
